version: "3.9"
services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - api
